version: '3'
services:
  app:
    build: .
    container_name: udemy-games
    volumes:
      - ./:/app
    ports:
      - "9201:8000"
    networks:
      - guess

networks:
  guess:
    external: true
