controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_games_create:
    path: /api/games
    controller: App\Controller\GamesController::create
    methods: POST
